'''A number is a perfect square, or a square number, if it is the square of a positive integer.
For example,  is a square number because    ; it is also an odd square.
The first 5 square numbers are: , and the sum of the odd squares is    .
Among the first 458 thousand square numbers, what is the sum of all the odd squares?'''

total = 0
for n in range(1, 458001):
    square = n * n
    
    if square % 2 == 1:
        total += square

print(total)

'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

a, b = 1, 1
total = 0
while a <= 4000000:
    if a % 2 == 0:
        total += a
    a, b = b, a + b
print(total)

'''What is the largest prime factor of the number 600851475143?'''

def largest_prime_factor(n):
    factor = 2
    while factor * factor <= n:
        if n % factor == 0:
            n //= factor
        else:
            factor += 1
    return n
print(largest_prime_factor(600851475143))